# Generated by Django 2.0.6 on 2018-06-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_logo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
