# Generated by Django 2.0.6 on 2018-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180613_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo_background',
            field=models.CharField(default='', max_length=255),
        ),
    ]
