# Generated by Django 2.0.6 on 2018-06-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
