# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('email_address', models.CharField(default='', max_length=255)),
                ('comments', models.TextField()),
            ],
        ),
    ]
