# Generated by Django 2.0.6 on 2018-06-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='comment',
            field=models.CharField(default='Testimonial Comment', max_length=500),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='full_name',
            field=models.CharField(default='Testimonial Full Name', max_length=255),
        ),
    ]
