# Generated by Django 2.0.6 on 2018-06-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20180613_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='comment',
            field=models.TextField(),
        ),
    ]
