# Generated by Django 2.0.6 on 2018-06-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_auto_20180613_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
